# Generated by Django 5.2.5 on 2025-09-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='To‘liq ism')),
                ('job_title', models.CharField(max_length=150, verbose_name='Kasb / Lavozim')),
                ('about', models.TextField(verbose_name='Qisqacha o‘zim haqimda')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profil rasmi')),
                ('hero_bg', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Fon rasmi')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Tug‘ilgan sana')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shahar')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Yosh')),
                ('degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ma’lumot')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('freelance', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=20, verbose_name='Freelance holati')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Loyiha nomi')),
                ('category', models.CharField(max_length=100, verbose_name='Turkum')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Rasm')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='Havola')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150, verbose_name='Kasb nomi')),
                ('company', models.CharField(max_length=200, verbose_name='Kompaniya')),
                ('start_year', models.CharField(max_length=10, verbose_name='Boshlanish')),
                ('end_year', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tugash')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150, verbose_name='Daraja / Kurs')),
                ('institution', models.CharField(max_length=200, verbose_name='O‘quv yurti')),
                ('start_year', models.CharField(max_length=10, verbose_name='Boshlanish')),
                ('end_year', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tugash')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Xizmat nomi')),
                ('description', models.TextField(verbose_name='Xizmat haqida')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ikonka (masalan: bi bi-laptop)')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Skill nomi')),
                ('percentage', models.PositiveIntegerField(verbose_name='Foiz (0-100)')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='Platforma nomi (masalan: Telegram, GitHub)')),
                ('icon', models.CharField(max_length=50, verbose_name='Ikonka (masalan: bi bi-github)')),
                ('url', models.URLField(verbose_name='Havola')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nom')),
                ('value', models.PositiveIntegerField(verbose_name='Qiymat')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='portfolio.profile')),
            ],
        ),
    ]
